Import('qt_env')

env = qt_env.Clone()

# Shouldn't this be GAMEFALLOUT3_LIBRARY
env.AppendUnique(CPPDEFINES = [ 'GAMESTARFIELD_LIBRARY' ])

env.RequiresGamebryo()

lib = env.SharedLibrary('gamestarfield', env.Glob('*.cpp'))
env.InstallModule(lib)

res = env['QT_USED_MODULES']
Return('res')
